version: '3.5'
services:
  gogs:
    container_name: gogs
    image: "gogs/gogs-rpi"
    networks:
      - gogs
    extra_hosts:
      - "ares.motofans.club:10.0.0.159"
    ports:
      - "2222:22"
      - "3000:3000" 
    volumes:
      - "./gogs-data:/data"
    restart: unless-stopped

networks:
  gogs:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.22.0/24

