version: '3'

services:

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    network_mode: host

  jumpserver:
    image: daocloud.io/subaru/jumpserver
    container_name: jumpserver
    depends_on:
      - redis
    restart: always
    environment:
      DB_HOST: 127.0.0.1
      DB_USER: jumpserver
      DB_PASSWORD: jumpserver
      DB_NAME: jumpserver
      REDIS_HOST: 127.0.0.1
    network_mode: host
    volumes:
      - jms_data:/opt/jumpserver/data

  nginx-luna:
    image: daocloud.io/subaru/nginx-luna
    container_name: nginx_luna
    depends_on:
      - jumpserver
    restart: always
    network_mode: host
    volumes:
      - jms_data:/opt/jumpserver/data
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  jms_data:
