#! /bin/bash

if [ $# -eq 0 ]
then
  echo "Need a client name"
  exit 1
fi

if [ ! -e /.ready ]
then
  echo "No, not yet. I am not ready.. please try again in a minute or two.."
  exit 1
fi

client=$1
client_ip=$2

if [ -e /wg/clients/${client} ]
then
  echo "Client ${client} already exists"
  exit 1
fi

cd /etc/wireguard

wg genkey | tee ${client}_private_key | wg pubkey > ${client}_public_key

client_pvtkey=$(cat /etc/wireguard/${client}_private_key)
client_pubkey=$(cat /etc/wireguard/${client}_public_key)
server_pubkey=$(cat /etc/wireguard/server_public_key)
server_ip=$(curl -s icanhazip.com)

wg set wg0  peer ${client_pubkey} allowed-ips ${client_ip}

echo "Client added successfully"
